# Generated by Django 3.0.5 on 2020-04-17 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 15, 52, 58, 989831), verbose_name='date published'),
        ),
    ]
