# Generated by Django 3.0.5 on 2020-04-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200418_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_imageurl',
            field=models.CharField(default='static/main/images/no-image.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_link',
            field=models.CharField(blank=True, default='https://en.wikipedia.org/wiki/JetBlue', max_length=200, null=True),
        ),
    ]
