# Generated by Django 3.0.5 on 2020-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200424_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_has_twitter_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
